### ISSUE TITLE
WOW!

### ISSUE THREAD

**Issue by TGR696** [midraal/plugin.video.jen#5]
First things first, what a great addon! Thank you for all the hard work!
 
I have 1 question. When the streams are being loaded it seems i can't move to the right with my arrow keys for skipping per page or to press cancel. Works only with mouse control. Is this on my end? Am i doing something wrong? I can only go up or down with my keys/remote control
Screenshot:  https://imgur.com/Ch9VReq
If you need more info i would be more than happy to help.
Thank you!

**Comment by midraal** [comment]
no, it's a bug in nanscrapers dialog implementation. it's on the to do list, but not seeing where the issue is at first glance

**Comment by TGR696** [comment]
Thank you for the comment! Again, great work!
