### ISSUE TITLE
2 Problems I've come across

### ISSUE THREAD

**Issue by simonsez33** [midraal/plugin.video.jen#6]
Afternoon, Firstly thank you for creating a user friendly addon thats available for the community. 

I've come across 2 bugs / problems:-

1. In creating a list of sublinks within an item. It seems to add a "search" link at the end of the list when I've not added it to the code.

2. Also i cant seem to get rtmp files to playback. Kodi log shows these errors.

plugin.video.jen\default.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmc::PlayerXBMCAddon::xbmc::Player

Hope this can be looked into.

Again thanks for the work so far i love it. Ive Just contacted Dabutcher to be added to the support group

Simon

**Comment by midraal** [comment]
plugin.video.jen\default.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmc::PlayerXBMCAddon::xbmc::Player doesn't have anything to do with rtmp

and you'll need to write plugins to fix those issues
